services:
  - type: web
    name: molayman-lottery-foundation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask --app wsgi:app db upgrade && gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: AUTO_CREATE_DB
        value: "false"
      - key: MAIL_SERVER
        value: ""
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        value: ""
      - key: MAIL_PASSWORD
        value: ""
      - key: MAIL_DEFAULT_SENDER
        value: ""
